### ISSUE TITLE
You provided no sources for F-Droid issues

### ISSUE THREAD

**Issue by realguyman** [Wonderfall/wonderfall.github.io#1]
https://github.com/Wonderfall/wonderfall.github.io/blob/e05a5843124bf99d4518661a1a47258530acc8a7/content/posts/fdroid-issues.md?plain=1#L14

Despite your notice that "this article is sourced from official and trusted sources" I see no links to supposed sources to support numerous claims you've made. Could you add them, please?

**Comment by Wonderfall** [comment]
The links are scattered throughout the article where they make sense, instead of putting everything at the bottom for no reason.
